In [7]:
### Вычисления с помощью Numpy

In [8]:
### Задание 1

In [9]:
import numpy as np

In [10]:
a = np.array([[1, 2, 3, 3, 1],
             [6, 8, 11, 10, 7]])

In [11]:
a = a.transpose()
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [12]:
mean_a = np.array([0, 0])
np.mean(a, axis = 0, out = mean_a)
mean_a

array([2, 8])

In [13]:
### Задание 2

In [14]:
a_centered = a - mean_a
a_centered

array([[-1, -2],
       [ 0,  0],
       [ 1,  3],
       [ 1,  2],
       [-1, -1]])

In [15]:
### Задание 3

In [16]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1]) / 4
a_centered_sp


2.0

In [17]:
### Задание 4

In [18]:
np.cov(a.transpose())

array([[1. , 2. ],
       [2. , 4.3]])

In [19]:
### Работа с данными в Pandas

In [20]:
### Задание 1

In [21]:
import pandas as pd
authors = pd.DataFrame({'author_id': [1, 2, 3], 'author_name': ['Тургенев', 'Чехов', 'Островский']}, columns = ['author_id', 'author_name'])
books = pd.DataFrame({'author_id': [1, 1, 1, 2, 2, 3, 3], 'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 'price': [450, 300, 350, 500, 450, 370, 290]}, columns = ['author_id', 'book_title', 'price'])

In [22]:
### Задание 2

In [23]:
authors_price = pd.merge(authors, books, on = 'author_id', how = 'inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [24]:
### Задание 3

In [25]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [26]:
### Задание 4

In [27]:
authors_stat = authors_price.groupby('author_id').min()
authors_stat.rename(columns={'price':'min_price'}, inplace=True)
authors_stat['max_price'] = authors_price.groupby('author_id').max()['price']
authors_stat['mean_price'] = authors_price.groupby('author_id').mean()['price']
authors_stat.drop('book_title', 1, inplace=True)
authors_stat.reset_index(drop=True, inplace=True)
authors_stat

author_name  min_price  max_price  mean_price
0    Тургенев        300        450  366.666667
1       Чехов        450        500  475.000000
2  Островский        290        370  330.000000

In [28]:
### Задание 4

In [29]:
authors_price.insert(4, "cover", ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'])


In [30]:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'], columns=['cover'], aggfunc=np.sum, fill_value=0)
book_info.to_pickle("./book_info.pkl")
book_info2 = pd.read_pickle("./book_info.pkl")
book_info.equals(book_info2)

True